### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by zaccharieramzi** [wustl-cig/ELDER#1]
Hi,

Thank you so much for this repo: I was able to run it and get almost the same results as the paper in no-time (less than 2 hours), so I was really happy :)

I was wondering if it was possible to get access to the training data, either with a direct download link or google drive, or with instructions (potentially a script) to assemble it as I understand it's a non-trivial combination of multiple datasets.

From the paper I read:
> We employ the color image training dataset in [37], which is a combination of the 400 CBSD
images, 4,744 images of Waterloo Exploration Database [45], 900 images from DIV2K dataset, and
2,750 images from Flickr2K dataset

I would basically like to get the performance of the models on the training dataset (not retrain) for my own research. Happy to chat about it if you are interested.

**Comment by JiamingLiu-Jeremy** [comment]
Hi zaccharieramzi, 

Thanks for showing interest to our work. Please find the training dataset in [Google drive](https://drive.google.com/file/d/1WVTgEBZgYyHNa2iVLUYwcrGWZ4LcN4--/view?usp=sharing). Thanks [GSPnP](https://github.com/samuro95/GSPnP) for gathering this dataset.

The training code is on the way.
